name: Check Solvex Lunar
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-lunar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # 1) Force DNS sur le runner via /etc/resolv.conf
      - name: Force DNS to 1.1.1.1
        run: |
          echo 'nameserver 1.1.1.1' | sudo tee /etc/resolv.conf
          cat /etc/resolv.conf

      # 2) Installation éventuelle de dépendances si besoin
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3

      # 3) Exécuter le script Python
      - name: Run check_solvex_test
        run: |
          python3 check_solvex_test.py

      # 4) Afficher le log
      - name: Show log
        run: |
          echo "===== check_solvex_test.log ====="
          cat check_solvex_test.log || echo "No log file found."