name: Build CSV and Commit

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Config Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run build_csv
        run: |
          echo "==== Running build_csv.py ===="
          python build_csv.py
          echo "==== End build_csv ===="

      - name: Show CSV lines
        run: |
          if [ -f "training_data.csv" ]; then
            echo "First lines of CSV :"
            head -n 10 training_data.csv
          else
            echo "No CSV found"
          fi

      - name: Commit and Push CSV
        run: |
          if [ -f "training_data.csv" ]; then
            echo "training_data.csv found => commit & push"
            git add training_data.csv
            git commit -m "Auto-update training_data.csv [skip ci]" || echo "Nothing to commit."
            git push origin main
          else
            echo "No training_data.csv => skip commit."
          fi