name: Build CSV and Push

on:
  workflow_dispatch:
    # Permet de déclencher manuellement le workflow depuis l'onglet Actions
  push:
    branches:
      - main
    # On peut éventuellement exclure le commit auto s'il correspond à un message défini
    #    (ex: si on ne veut pas re-déclencher le workflow pour le commit "Auto-update training_data.csv")
    # Cela se fait avec:
    # branches-ignore:
    #   - main
    # 
    # OU:
    # paths-ignore:
    #   - 'training_data.csv'

jobs:
  build-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          # ci-dessus : "false" si l'on veut soi-même configurer git plus loin,
          # mais on peut laisser "true" si on veut que la config GitHub TOKEN soit auto.

      - name: Configure git (pour utiliser GITHUB_TOKEN)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # force la branche main ou autre
          git checkout main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          # Ajustez selon vos besoins; ex: pip install pandas requests

      - name: Run build_csv.py
        run: |
          echo "==== Running build_csv.py ===="
          python build_csv.py
          echo "==== End build_csv ===="

      - name: Show generated CSV
        run: |
          echo "Content (head) of training_data.csv :"
          head -n 20 training_data.csv
          echo "===="

      - name: Commit and Push CSV
        if: always()
        run: |
          # S'il n'existe pas => pas de commit
          if [ -f "training_data.csv" ]; then
            echo "training_data.csv found => commit & push"
            # On commit le CSV
            git add training_data.csv
            git commit -m "Auto-update training_data.csv [skip ci]"
            # On push via GITHUB_TOKEN
            git push origin HEAD:main
          else
            echo "No training_data.csv => skip commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}