name: Build CSV and Push

# Déclencheurs :
on:
  workflow_dispatch:
    # permet de lancer manuellement
  push:
    branches:
      - main
    # vous pouvez exclure plus finement si besoin

permissions:
  contents: write  # important : autorise l'écriture (push) sur le repo

jobs:
  build-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0
        # persist-credentials: true => permet de conserver les credentials
        # fetch-depth: 0 => on récupère tout l'historique, parfois nécessaire si on veut pusher

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Vérifie qu'on est bien sur la branche main
          git checkout main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          # ajustez selon vos besoins (pandas, requests, etc.)

      - name: Run build_csv.py
        run: |
          echo "==== Running build_csv.py ===="
          python build_csv.py
          echo "==== End build_csv ===="

      - name: Show generated CSV
        run: |
          if [ -f "training_data.csv" ]; then
            echo "===== training_data.csv HEAD ====="
            head -n 20 training_data.csv
            echo "===== End of HEAD ====="
          else
            echo "No training_data.csv found."
          fi

      - name: Commit and Push CSV
        if: always()
        run: |
          if [ -f "training_data.csv" ]; then
            echo "training_data.csv found => commit & push"
            git add training_data.csv
            # [skip ci] ou [ci skip] n'est pas officiellement géré par GH Actions,
            # mais c'est inoffensif si vous voulez un tag dans le message.
            git commit -m "Auto-update training_data.csv [skip ci]" || echo "Nothing to commit."
            git push origin main
          else
            echo "No training_data.csv => skip commit."
