name: CheckSolvexTestDNS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-lunarcrush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1) Désactiver systemd-resolved et écraser /etc/resolv.conf
      - name: Force DNS to 8.8.8.8
        run: |
          echo "Stopping and disabling systemd-resolved..."
          sudo systemctl stop systemd-resolved
          sudo systemctl disable systemd-resolved
          echo "Removing symlink /etc/resolv.conf if any..."
          sudo rm -f /etc/resolv.conf
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
          cat /etc/resolv.conf

      # 2) Installer Python + dépendances (si besoin)
      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      # 3) Exécuter le script Python check_solvex_test.py
      - name: Run check_solvex_test
        run: |
          python3 check_solvex_test.py

      # 4) Affichage du log
      - name: Show log
        run: |
          echo "===== check_solvex_test.log ====="
          cat check_solvex_test.log || echo "No log file found."