name: Check Solvex Endpoints

on:
  # Le déclencheur "workflow_dispatch" permet de lancer manuellement
  # ce workflow via l'onglet "Actions" dans GitHub.
  workflow_dispatch:

jobs:
  check-solvex:
    runs-on: ubuntu-latest
    steps:
      # 1) Récupère votre code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Configure l'environnement Python 3.x
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3) Installer les dépendances éventuelles (requests, etc.)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4) Exécuter le script check_solvex_endpoints.py
      - name: Run check_solvex_endpoints
        run: python check_solvex_endpoints.py

      # 5) Afficher le log dans la console Actions
      - name: Show check_solvex_endpoints.log
        # "|| echo" permet de ne pas échouer si le fichier est introuvable
        run: cat check_solvex_endpoints.log || echo "No log file found."