name: Build CSV and Train ML

on:
  workflow_dispatch:    # Permet de déclencher manuellement l’action depuis l’onglet "Actions"

jobs:
  build-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print config.yaml for debug
        run: |
          echo "===== CONFIG.YAML ====="
          cat config.yaml
          echo "======================="
      
      - name: Run build_csv.py
        run: |
          echo "===== Launch build_csv ====="
          python build_csv.py
          echo "===== End build_csv ====="

      - name: Show build_csv.log
        if: always()
        run: |
          echo "===== build_csv.log content ====="
          cat build_csv.log || echo "No build_csv.log found."
          echo "================================="

      - name: Check if training_data.csv is generated
        run: |
          ls -l training_data.csv || echo "No training_data.csv found"

      - name: Run train_model.py
        run: |
          echo "===== Launch train_model ====="
          python train_model.py
          echo "===== End train_model ====="

      - name: Show model.pkl
        run: |
          echo "===== Checking model.pkl ====="
          ls -l model.pkl || echo "No model.pkl found."