name: Build and Train Pipeline

on:
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests pandas scikit-learn joblib ta

      - name: Run build_csv
        run: |
          python build_csv.py

      - name: Show CSV
        run: |
          echo "===== HEAD of CSV ====="
          head training_data.csv || echo "No CSV found."

      - name: Upload CSV
        uses: actions/upload-artifact@v3
        with:
          name: training_data_csv
          path: training_data.csv

  train_and_save:
    runs-on: ubuntu-latest
    needs: build_and_run   # on dépend du job build_and_run (celui-ci doit finir avant)
    steps:
      - uses: actions/checkout@v3

      - name: Download CSV Artifact
        uses: actions/download-artifact@v3
        with:
          name: training_data_csv
          path: .

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests pandas scikit-learn joblib ta

      - name: Ensure CSV exists
        run: |
          ls -l training_data.csv || echo "No CSV found"

      - name: Train Model
        run: |
          python train_model.py

      - name: Show Logs
        run: |
          echo "===== TRAIN LOGS ====="
          cat train_model.log || echo "No log found."

      - name: Upload Model
        uses: actions/upload-artifact@v3
        with:
          name: model_pkl
          path: model.pkl