name: Train Model

on:
  workflow_dispatch:

jobs:
  train_and_save:
    runs-on: ubuntu-latest
    steps:
      # 1) Récupération du code source
      - uses: actions/checkout@v3

      # 2) Téléchargement du CSV s'il est dans un artifact
      - name: Download CSV Artifact
        uses: actions/download-artifact@v3
        with:
          name: training_data_csv
          path: .

      # 3) Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4) Installer les dépendances
      - name: Install Dependencies
        run: |
          pip install requests pandas scikit-learn joblib ta

      # 5) Vérifier qu'on a le CSV
      - name: Ensure CSV exists
        run: |
          ls -l training_data.csv || echo "No CSV found"

      # 6) Lancer l'entraînement
      - name: Train Model
        run: |
          python train_model.py

      # 7) Afficher le log
      - name: Show Logs
        run: |
          echo "===== TRAIN LOGS ====="
          cat train_model.log || echo "No log found."

      # 8) Uploader le modèle entraîné
      - name: Upload Model
        uses: actions/upload-artifact@v3
        with:
          name: model_pkl
          path: model.pkl